language: ruby
rvm:
  - 1.8.7
  - 1.9.2
  - 1.9.3
  - jruby-18mode # JRuby in 1.8 mode
  - jruby-19mode # JRuby in 1.9 mode
  - rbx-18mode
script: rake test
gemfile:
  - Gemfile.rake-0.8.7
  - Gemfile.rake-0.9.2.2
